name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      # Opcional: fija el video del test si quieres cambiarlo en CI
      # TEST_VIDEO_ID: "YRmc0-dlDgM"
      # TEST_VIDEO_URL: "https://www.youtube.com/watch?v=YRmc0-dlDgM"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project deps (creates .venv)
        run: |
          make install
          . .venv/bin/activate && python -V
          . .venv/bin/activate && pip list

      - name: Use yt-dlp master (for --impersonate)
        run: |
          make use-ytdlp-master
          make ytdlp-version

      # Opcional: si el repo usa datos de ejemplo, crea carpetas
      - name: Ensure data dirs
        run: |
          mkdir -p data/tests/enus

      - name: Run smoke test (en-US)
        run: |
          make test-enus

      - name: Run full test suite
        run: |
          make test